image: node:18

pipelines:
  branches:
    dev:
      - step:
          name: Build and Deploy to Dev
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - npm ci
            - npm run build:dev
            - ls -la dist-dev   # List the contents of the dist folder to ensure it exists and contains service-worker.js
            - firebase deploy --only hosting:dev-site --token $FIREBASE_TOKEN_DEV
    main:
      - step:
          name: Build and Deploy to Prod
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - npm ci
            - npm run build:prod
            - ls -la dist   # List the contents of the dist folder to ensure it exists and contains service-worker.js
            - firebase deploy --only hosting:prod-site --token $FIREBASE_TOKEN_PROD
